### ISSUE TITLE
Home Assistant freezes and must be power cycled if there is a power state mismatch

### ISSUE THREAD

**Issue by binarylogic** [iloveicedgreentea/madvr-envy-homeassistant#10]
There seem to be broad issues with state management if MadVR changes state outside of the remote provided by this integration (i.e., #9).

In this case, this integration can completely freeze Home Assistant, requiring a power cycle. Here are the steps to reproduce this:

1. Turn on MadVR using the remote in Home Assistant provided by this integration.
2. Turn off MadVR directly, either using the MadVR remote or the button on the front of the unit.
3. Observe that the remote in Home Assistant does not update.
4. Turn off MadVR using the remote in Home Assistant.
5. Home Assistant freezes. It's likely stuck in an infinite loop trying to power off MadVR.

**Comment by iloveicedgreentea** [comment]
Are you saying this causes HA core to freeze?

**Comment by binarylogic** [comment]
Yes, HA becomes completely unresponsive. I have to power cycle HA to get things working again.

**Comment by iloveicedgreentea** [comment]
okay I will investigate

**Comment by binarylogic** [comment]
Thanks. I'm done for the day, but I'll also take a look in the morning and try to submit a fix.

**Comment by iloveicedgreentea** [comment]
try 1.5.2.1 beta version, seems to work for me

**Comment by binarylogic** [comment]
Thanks. I enabled beta versions and installed `1.5.2.2` since that was the latest version. I'm still having the same problem:

1. Turn on the Envy and ensure the `envy` remote in HA provided by this integration is on as well.
2. Physically turn off the Envy, wait ~15 seconds of the envy to full power off.
3. Turn the `envy` remote in HA off.
4. HA freezes. A hard reboot is required to make it responsive again.

**Comment by iloveicedgreentea** [comment]
what about [v1.5.2.3](https://github.com/iloveicedgreentea/madvr-envy-homeassistant/releases/tag/v1.5.2.3)

**Comment by binarylogic** [comment]
Still freezes, but now it freezes when I start HA. I had to restart HA in safe mode, SSH in, and manually rollback the integration to get HA working again. That was not a fun experience.

I took a look at the code, and there's a fundamental misunderstanding around how async in Python and Home Assistant works. The design should account for state changes that can happen at any time outside of HA, including power state changes. It appears that this integration gets stuck in a reconnect loop when the connection dies. I'd fix it, but the overall approach to async is fundamentally off.

> I strongly disagree with their deployment model for integrations.

I read that in the README. Their deployment model exists to prevent the exact issues I'm having here. It's not a great experience to brick your HA due to an integration. I was fortunate enough to have setup SSH access. I agree it's cumbersome, and I'm going through it with [my integration](https://github.com/binarylogic/trinnov-altitude-homeassistant), but I'd encourage you to push through it. Otherwise, I'd slap a big warning on the README instructing users to perform a backup and ensure SSH is setup.

**Comment by iloveicedgreentea** [comment]
This is unnecessarily dramatic and unhelpful. SSH is not required at all since you can exec or console into HA no matter where you have it deployed.

This uses async just fine. It has a callback to update the HA state when it receives notifications that the envy sends.

But anyway, since I work on this on my own time for free, I will fix this eventually then once I learn how to code 👍
