### ISSUE TITLE
unable to add remote to HA config

### ISSUE THREAD

**Issue by volkerrichert** [iloveicedgreentea/madvr-envy-homeassistant#13]
If i try to add the madvr remote config und test it, i allway get 

Fehler beim Aufrufen des Diensts homeassistant/reload_all. '_asyncio.Future' object has no attribute 'async_get_platform'

**Comment by iloveicedgreentea** [comment]
How do you know its this integration? 

I am able to add a new instance just now, no issues

Do you have more info? Logs? HA and integration version?

**Comment by volkerrichert** [comment]
hm, wo it's working fine. TNX
